"""create tle table

Revision ID: 1ff4058cc4a2
Revises: 
Create Date: 2026-06-03 11:11:41.051027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ff4058cc4a2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('satellite_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('line1', sa.String(length=69), nullable=False),
    sa.Column('line2', sa.String(length=69), nullable=False),
    sa.Column('source_group', sa.String(length=50), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('satellite_id', 'source_group')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tle')
    # ### end Alembic commands ###
